### ISSUE TITLE
Links are not displaying properly in outlook web

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dhis2-newsletter#19]
They don't display as hyperlinks [WAIT CONFIRMATION]

**Comment by adrianq** [comment]
Fix links in DHIS2 internal message for subscription/mentioning

See https://github.com/EyeSeeTea/interpretation-notification/issues/13

For master and 2.30

**Comment by tokland** [comment]
Internal PR (for 2.30): https://github.com/EyeSeeTea/dhis2-core/pull/58

https://jira.dhis2.org/browse/DHIS2-5468
