### ISSUE TITLE
Deploy PSI dhis-Newsletter targeting leap

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/dhis2-newsletter#5]
- [x] Check triggers
- [x] Check scripts
- [x] Set crons (every 10 mins notifications, Sunday 22 UTC newsletter -> for now every day to test)

**Comment by adrianq** [comment]
- [x] Deploy interpretation app
- [x] Re-configure newsletter [WAIT for app.interpretations user]
- [x] Apply triggers in leap.
